config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: "countries#index"

  resources :users

  resources :countries

end

app/models/country.rb
class Country < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :live_city

  validates :live_city_id, numericality: { other_than: 0 } 

  belongs_to :user

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
    @country = Country.new
  end

  def new
    @country = Country.new
    @users = User.all
  end

  def create
  end


end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/index.html.erb
<div class="all-bg">
  <%= render "shared/header" %>
  <div class="index-title">
      <p class="it-1">身近にいる、特別な人</p>
      <p class="it-2">海外に出ている日本人は意外と多い</p>
      <p class="it-2">そんな人と話してみませんか？</p>
  </div>

  <%# 国一覧 %>
  <div class="search">
    <%= form_with model: @country, url: new_country_path, local: true do |f| %>
      <%= f.collection_select(:live_city_id, LiveCity.all, :id, :name, {}, {class:"live-city-select"}) %>
    <% end %>
    <%= link_to new_country_path do %>
      <button class="country-btn">移動</button>
    <% end %>
  </div>

  <%# 人気旅行先 %>
  <div class='favorite'>
    <h2 class="title">
      人気旅行先
    </h2>
    <ul class='favorite-lists'>
      <li class='list'>
        <%= image_tag "favorite-1.png", class:"list-pic" %>
        <span class='list-number'>1</span>
        <h3 class='list-text'>
          <span class='list-blue-text'>グアム</span>
          （アメリカ）
        </h3>
        <p class='list-description'>
          世界中から観光客が集まる観光地！　ビーチだけでなく、隠れた魅力がたくさん詰まっています！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "favorite-2.png", class:"list-pic" %>
        <span class='list-number'>2</span>
        <h3 class='list-text'>
          <span class='list-blue-text'>ソウル</span>
          （韓国）
        </h3>
        <p class='list-description'>
          近代的な超高層ビルやハイテクな地下鉄、ポップ カルチャーと、仏教寺院、古宮、昔ながらの露天市が混在する、巨大なメトロポリスです！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "favorite-3.png", class:"list-pic" %>
        <span class='list-number'>3</span>
        <h3 class='list-text'>
          <span class='list-blue-text'>バンコク</span>
          （タイ）
        </h3>
        <p class='list-description'>
          物価が安く治安も悪くないことから世界中の旅行者が訪れるタイの首都。毎年2000万人もの外国人観光客が訪れており、「世界航行先ランキング」では2016年より3年連続で世界一となっています！
        </p>
      </li>
    </ul>
  </div>

    <%= render "shared/footer" %>
</div>

app/views/countries/new.html.erb
<div class="america-bg">
  <%= render "shared/header" %>

  <h3 class="america-title">アメリカ</h3>

<%# ユーザー一覧 %>
  <div class='user-name-list'>
    <h2 class='user-title'>ユーザー一覧</h2>
    <ul class='user-lists'>
      <% @users.each do |users| %>
        <li class='list'>
          <div class='user-info'>
            <h3 class='all-user-list'>
            <%= link_to users.name, user_path(users.id), class: "user-list" %>
            </h3>
          </div>
        </li>
      <% end %>
    <%# ユーザー登録がない場合 %>
      <% if @users.length == 0 %>
        <h3>
          滞在者はいません
        </h3>
      <% end %>
    </ul>
  </div>
<%# チャット画面のみログイン必須 %>

  <%= render "shared/footer" %>
</div>